title: Im learning!
author: Ramon
email: rfm1@live.nl
description: > # this means to ignore newlines until "baseurl:"
  Im learning github pages! **_AWESOME!_**

# social links
twitter_username: your-twitter-handle
github_username:  Ramon96

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
